language: ruby
sudo: false
cache: bundler
rvm:
  - 2.5.0
services: postgresql
env:
  global:
    - SECRET_KEY=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
  running_on_ci: true
script:
  - mv config/database.yml{.travis,}
  - RAILS_ENV=test bundle exec rails --trace db:migrate spec
before_script:
  - psql -c 'create database call4paperz_test' -U postgres
  - "ruby -run -e httpd spec/fixtures/ -p 3101 &"
addons:
  code_climate:
    repo_token: e03721617acfa792a2a2909eb7cf44abd5352d2f287a56483a0894ef22e1a29b

