development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: call4paperz_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: call4paperz_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: call4paperz_production
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock
